name: Keep Servers serv00
on:
  schedule:
   - cron: '0 15 */8 * *'
  workflow_dispatch: 

jobs:
  keep_servers_alive:
    runs-on: ubuntu-latest
    env:
      ACCOUNTS: >
        [
        {"SSH_USER":"123456789", "SSH_PASS":"123456", "HOST":"sxxx.serv00.com"}
        ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass jq

      - name: Process each account
        run: |
           echo "*****************************************************"
           echo "*****************************************************"
echo "GitHub Project: github.com/anyagixx/proxme3"
echo "Original Author Blog: ygkkk.blogspot.com"
echo "Original Author YouTube: www.youtube.com/@ygkkk"
           echo "VPS Server Remote SSH Login Script [GitHub]"
           echo "*****************************************************"
           echo "*****************************************************"
            count=0  
           for account in $(echo "${ACCOUNTS}" | jq -c '.[]'); do
              count=$((count+1))
              SSH_USER=$(echo $account | jq -r '.SSH_USER')
              SSH_PASS=$(echo $account | jq -r '.SSH_PASS')
              HOST=$(echo $account | jq -r '.HOST')
           if sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no "$SSH_USER@$HOST" -q exit; then
            echo "Congratulations! Server #[$count] connected successfully! Server address: $HOST, Account name: $SSH_USER" 
           else
            echo "===================================================="
            echo "Unfortunate! Server #[$count] connection failed! Server address: $HOST, Account name: $SSH_USER"
            echo "Warning: Possible incorrect account name, password, server name, or current server is under maintenance"  
            echo "===================================================="
           fi
           sleep 10
            done
